export const patterns = [
  {
    id: "two-pointers",
    title: "1. Two Pointers",
    questions: [
      { id: "tp-1", name: "Pair with Target Sum", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description/" }] },
      { id: "tp-2", name: "Rearrange 0 and 1", difficulty: "medium", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/segregate-0s-and-1s5106/1" }] },
      { id: "tp-3", name: "Remove Duplicates", difficulty: "easy", links: [{ label: "LC #1", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/" }, { label: "LC #2", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/" }, { label: "LC #3", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/" }] },
      { id: "tp-4", name: "Squaring a Sorted Array", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/squares-of-a-sorted-array/" }] },
      { id: "tp-5", name: "Triplet Sum to Zero", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/3sum/" }] },
      { id: "tp-6", name: "Triplet Sum Close to Target", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/3sum-closest/" }] },
      { id: "tp-7", name: "Triplets with Smaller Sum", difficulty: "medium", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/count-triplets-with-sum-smaller-than-x5549/1" }] },
      { id: "tp-8", name: "Subarrays with Product Less than a Target", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/subarray-product-less-than-k/" }] },
      { id: "tp-9", name: "Dutch National Flag Problem", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/sort-colors/description/" }] },
      { id: "tp-10", name: "Quadruple Sum to Target", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/4sum/" }] },
      { id: "tp-11", name: "Comparing Strings containing Backspaces", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/backspace-string-compare/" }] },
      { id: "tp-12", name: "Minimum Window Sort", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/shortest-unsorted-continuous-subarray/" }, { label: "iDeserve", url: "https://www.ideserve.co.in/learn/minimum-length-subarray-sorting-which-results-in-sorted-array" }] },
    ],
  },
  {
    id: "fast-slow-pointers",
    title: "2. Fast & Slow Pointers",
    questions: [
      { id: "fsp-1", name: "LinkedList Cycle", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/linked-list-cycle/" }] },
      { id: "fsp-2", name: "Start of LinkedList Cycle", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/linked-list-cycle-ii/" }] },
      { id: "fsp-3", name: "Happy Number", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/happy-number/" }] },
      { id: "fsp-4", name: "Find Duplicate Number", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-the-duplicate-number/description/" }] },
      { id: "fsp-5", name: "Middle of the LinkedList", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/middle-of-the-linked-list/" }] },
      { id: "fsp-6", name: "Palindrome LinkedList", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/palindrome-linked-list/" }] },
      { id: "fsp-7", name: "Rearrange a LinkedList", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/reorder-list/" }] },
      { id: "fsp-8", name: "Cycle in a Circular Array", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/circular-array-loop/" }] },
    ],
  },
  {
    id: "sliding-window",
    title: "3. Sliding Window",
    questions: [
      { id: "sw-1", name: "Maximum Sum Subarray of Size K", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/max-sum-subarray-of-size-k5313/1" }] },
      { id: "sw-2", name: "Smallest Subarray with a given sum", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/minimum-size-subarray-sum/" }] },
      { id: "sw-3", name: "Longest Substring with K Distinct Characters", difficulty: "medium", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1" }] },
      { id: "sw-4", name: "Fruits into Baskets", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/fruit-into-baskets/" }] },
      { id: "sw-5", name: "No-repeat Substring", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" }] },
      { id: "sw-6", name: "Longest Substring with Same Letters after Replacement", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/longest-repeating-character-replacement/" }] },
      { id: "sw-7", name: "Longest Subarray with Ones after Replacement", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/max-consecutive-ones-iii/" }] },
      { id: "sw-8", name: "Minimum Size Subarray Sum", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/minimum-size-subarray-sum/" }] },
      { id: "sw-9", name: "Minimum Window Substring", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/minimum-window-substring/description/?envType=study-plan-v2&envId=top-interview-150" }] },
      { id: "sw-10", name: "Permutation in a String", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/permutation-in-string/" }] },
      { id: "sw-11", name: "String Anagrams", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-all-anagrams-in-a-string/" }] },
      { id: "sw-12", name: "Words Concatenation", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/" }] },
    ],
  },
  {
    id: "kadane",
    title: "4. Kadane's Pattern",
    questions: [
      { id: "kd-1", name: "Maximum Subarray Sum", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-subarray/" }] },
      { id: "kd-2", name: "Minimum Subarray Sum", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/smallest-sum-contiguous-subarray/1" }] },
      { id: "kd-3", name: "Maximum Product Subarray", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-product-subarray/" }] },
      { id: "kd-4", name: "Maximum Subarray Sum with One Deletion", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-subarray-sum-with-one-deletion/description/" }] },
      { id: "kd-5", name: "Maximum Absolute Sum of Any Subarray", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-absolute-sum-of-any-subarray/" }] },
      { id: "kd-6", name: "Maximum Sum in Circular Array", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-sum-circular-subarray/" }] },
    ],
  },
  {
    id: "prefix-sum",
    title: "5. Prefix Sum",
    questions: [
      { id: "ps-1", name: "Subarray Sum Equals K", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/subarray-sum-equals-k/description/" }] },
      { id: "ps-2", name: "Find Pivot Index", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-pivot-index/description/" }] },
      { id: "ps-3", name: "Subarray Sums Divisible By K", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/subarray-sums-divisible-by-k/description/" }] },
      { id: "ps-4", name: "Contiguous Array", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/contiguous-array/description/" }] },
      { id: "ps-5", name: "Shortest Subarray With Sum at Least K", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/description/" }] },
      { id: "ps-6", name: "Count Range Sum", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/count-of-range-sum/description/" }] },
    ],
  },
  {
    id: "merge-intervals",
    title: "6. Merge Intervals",
    questions: [
      { id: "mi-1", name: "Merge Intervals", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/merge-intervals/description/" }] },
      { id: "mi-2", name: "Insert Interval", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/insert-interval/" }] },
      { id: "mi-3", name: "Intervals Intersection", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/interval-list-intersections/description/" }] },
      { id: "mi-4", name: "Overlapping Intervals", difficulty: "medium", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/check-if-any-two-intervals-overlap-among-a-given-set-of-intervals/" }] },
      { id: "mi-5", name: "Minimum Meeting Rooms", difficulty: "hard", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/attend-all-meetings-ii/1" }] },
      { id: "mi-6", name: "Maximum CPU Load", difficulty: "hard", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/maximum-cpu-load-from-the-given-list-of-jobs/" }] },
      { id: "mi-7", name: "Employee Free Time", difficulty: "hard", links: [{ label: "CoderTrain", url: "https://www.codertrain.co/employee-free-time" }] },
    ],
  },
  {
    id: "cyclic-sort",
    title: "7. Cyclic Sort",
    questions: [
      { id: "cs-1", name: "Cyclic Sort", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/sort-an-array-which-contain-1-to-n-values-in-on-using-cycle-sort/" }] },
      { id: "cs-2", name: "Find the Missing Number", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/missing-number/" }] },
      { id: "cs-3", name: "Find all Missing Numbers", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/" }] },
      { id: "cs-4", name: "Find the Duplicate Number", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-the-duplicate-number/" }] },
      { id: "cs-5", name: "Find all Duplicate Numbers", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-all-duplicates-in-an-array/" }] },
      { id: "cs-6", name: "Find the Corrupt Pair", difficulty: "easy", links: [{ label: "TheCodingSimplified", url: "https://thecodingsimplified.com/find-currupt-pair/" }] },
      { id: "cs-7", name: "Find the Smallest Missing Positive Number", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/first-missing-positive/" }] },
      { id: "cs-8", name: "Find the First K Missing Positive Numbers", difficulty: "hard", links: [{ label: "TheCodingSimplified", url: "https://thecodingsimplified.com/find-the-first-k-missing-positive-number/" }] },
    ],
  },
  {
    id: "linkedlist-reversal",
    title: "8. In-place Reversal of a LinkedList",
    questions: [
      { id: "lr-1", name: "Reverse a LinkedList", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/reverse-linked-list/" }] },
      { id: "lr-2", name: "Reverse a Sub-list", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/reverse-linked-list-ii/" }] },
      { id: "lr-3", name: "Reverse List in Pairs", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/swap-nodes-in-pairs/description/" }] },
      { id: "lr-4", name: "Reverse every K-element Sub-list", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/reverse-nodes-in-k-group/" }] },
      { id: "lr-5", name: "Reverse nodes in EVEN Length Groups", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/reverse-nodes-in-even-length-groups/description/" }] },
      { id: "lr-6", name: "Rotate a LinkedList", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/rotate-list/" }] },
    ],
  },
  {
    id: "stack",
    title: "9. Stack",
    questions: [
      { id: "st-1", name: "Remove Adjacent Duplicates", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/description/" }] },
      { id: "st-2", name: "Balanced Parentheses", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/valid-parentheses/description/" }] },
      { id: "st-3", name: "Reverse a String", difficulty: "easy", links: [] },
      { id: "st-4", name: "Next Greater Element", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/next-greater-element-ii/description/" }] },
      { id: "st-5", name: "Daily Temperatures", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/daily-temperatures/" }] },
      { id: "st-6", name: "Remove Nodes From Linked List", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/remove-nodes-from-linked-list/" }] },
      { id: "st-7", name: "Remove All Adjacent Duplicates in String II", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/" }] },
      { id: "st-8", name: "Simplify Path", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/simplify-path/" }] },
      { id: "st-9", name: "Remove K Digits", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/remove-k-digits/" }] },
    ],
  },
  {
    id: "hash-maps",
    title: "10. Hash Maps",
    questions: [
      { id: "hm-1", name: "First Non-repeating Character", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/first-unique-character-in-a-string/" }] },
      { id: "hm-2", name: "Maximum Number of Balloons", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-number-of-balloons/" }] },
      { id: "hm-3", name: "Longest Palindrome", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/longest-palindrome/" }] },
      { id: "hm-4", name: "Ransom Note", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/ransom-note/" }] },
    ],
  },
  {
    id: "binary-search",
    title: "11. Binary Search",
    questions: [
      { id: "bs-1", name: "Binary Search Basic", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-search/" }] },
      { id: "bs-2", name: "Upper Bound / Ceiling", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/ceil-in-a-sorted-array/1" }] },
      { id: "bs-3", name: "First and Last Position", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" }] },
      { id: "bs-4", name: "Count Number of Occurrences", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/number-of-occurrence2259/1" }] },
      { id: "bs-5", name: "Search in Infinite Sorted Array", difficulty: "medium", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/find-position-element-sorted-array-infinite-numbers/" }] },
      { id: "bs-6", name: "Peak Index in Mountain", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/peak-index-in-a-mountain-array/" }] },
      { id: "bs-7", name: "Find Peak in Mountain Range", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-peak-element/" }] },
      { id: "bs-8", name: "Find Minimum in Rotated Sorted Array", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" }] },
      { id: "bs-9", name: "Find Number of Rotations to Sorted Array", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/rotation4723/1" }] },
      { id: "bs-10", name: "Search in Rotated Sorted Array", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/search-in-rotated-sorted-array/description/" }] },
      { id: "bs-11", name: "Koko Eating Bananas", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/koko-eating-bananas/" }] },
      { id: "bs-12", name: "Min Days to Make M Bouquets", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/" }] },
      { id: "bs-13", name: "Aggressive Cows", difficulty: "medium", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/aggressive-cows/1" }] },
      { id: "bs-14", name: "H Index II", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/h-index-ii/description/" }] },
      { id: "bs-15", name: "Max Candies to K Children", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-candies-allocated-to-k-children/description/" }] },
      { id: "bs-16", name: "Capacity to Ship Packages in D Days", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/description/" }] },
      { id: "bs-17", name: "Book Allocation Problem", difficulty: "hard", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1" }] },
      { id: "bs-18", name: "Split Largest Array", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/split-array-largest-sum/description/" }] },
      { id: "bs-19", name: "Search 2D Matrix", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/search-a-2d-matrix/" }] },
      { id: "bs-20", name: "Search 2D Matrix II", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/search-a-2d-matrix-ii/description/" }] },
      { id: "bs-21", name: "Kth Smallest in Sorted Matrix", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/description/" }] },
      { id: "bs-22", name: "Kth Smallest in Multiplication Table", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/description/" }] },
      { id: "bs-23", name: "Median of 2 Sorted Arrays", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/median-of-two-sorted-arrays/" }] },
    ],
  },
  {
    id: "heap",
    title: "12. Heap Pattern",
    questions: [
      { id: "hp-1", name: "Kth Smallest", difficulty: "medium", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/kth-smallest-element5635/1" }] },
      { id: "hp-2", name: "Kth Largest", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/kth-largest-element-in-an-array/description/" }] },
      { id: "hp-3", name: "Top K Frequent Elements", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/top-k-frequent-elements/description/" }] },
      { id: "hp-4", name: "Top K Frequent Words", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/top-k-frequent-words/description/" }] },
      { id: "hp-5", name: "K Closest Points to Origin", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/k-closest-points-to-origin/description/" }] },
      { id: "hp-6", name: "Find K Closest Elements", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-k-closest-elements/description/" }] },
      { id: "hp-7", name: "Kth Weakest Row in Matrix", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/description/" }] },
      { id: "hp-8", name: "Merge K Sorted Arrays", difficulty: "hard", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/merge-k-sorted-arrays/1" }] },
      { id: "hp-9", name: "Kth Smallest in Sorted Matrix", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/description/" }] },
      { id: "hp-10", name: "Last Stone Weight", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/last-stone-weight/description/" }] },
      { id: "hp-11", name: "CPU Task Scheduler", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/task-scheduler/description/" }] },
      { id: "hp-12", name: "Reorganize String", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/reorganize-string/" }] },
      { id: "hp-13", name: "Min Number of Refueling Stops", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/minimum-number-of-refueling-stops/description/" }] },
      { id: "hp-14", name: "IPO", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/ipo/description/" }] },
      { id: "hp-15", name: "Course Scheduler III", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/course-schedule-iii/description/" }] },
      { id: "hp-16", name: "Find Median in Data Stream", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/find-median-from-data-stream/description/" }] },
      { id: "hp-17", name: "Sliding Window Median", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/sliding-window-median/description/" }] },
    ],
  },
  {
    id: "recursion-backtracking",
    title: "13. Recursion & Backtracking",
    questions: [
      { id: "rb-1", name: "Fibonacci", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/fibonacci-number/description/" }, { label: "YouTube", url: "https://www.youtube.com/watch?v=j4wjZqzhMqc&t" }] },
      { id: "rb-2", name: "Check if String is Palindrome", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/palindrome-string0817/1" }, { label: "YouTube", url: "https://www.youtube.com/watch?v=j4wjZqzhMqc&t" }] },
      { id: "rb-3", name: "Check if Array is Sorted", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/check-if-an-array-is-sorted0701/1" }, { label: "YouTube", url: "https://www.youtube.com/watch?v=-gC-QEdpvO4" }] },
      { id: "rb-4", name: "Sum of Digits of a Number", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/sum-of-digits1742/1" }, { label: "YouTube", url: "https://www.youtube.com/watch?v=-gC-QEdpvO4" }] },
      { id: "rb-5", name: "Remove Occurrences of a Character in String", difficulty: "easy", links: [{ label: "GFG", url: "https://www.geeksforgeeks.org/problems/remove-all-occurrences-of-a-character-in-a-string/1" }, { label: "YouTube", url: "https://www.youtube.com/watch?v=-gC-QEdpvO4" }] },
      { id: "rb-6", name: "Generate Parentheses", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/generate-parentheses/description/" }] },
      { id: "rb-7", name: "Letter Combinations of Phone Number", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/description/" }, { label: "YouTube", url: "https://www.youtube.com/watch?v=IKfIT6uFOcs" }] },
      { id: "rb-8", name: "Permutations", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/permutations/description/" }] },
      { id: "rb-9", name: "Combination Sum", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/combination-sum/description/" }] },
      { id: "rb-10", name: "Palindrome Partitioning", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/palindrome-partitioning/description/" }] },
    ],
  },
  {
    id: "tree",
    title: "14. Tree Pattern",
    questions: [
      { id: "tr-1", name: "Inorder Traversal", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-tree-inorder-traversal/description/" }] },
      { id: "tr-2", name: "Preorder Traversal", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-tree-preorder-traversal/description/" }] },
      { id: "tr-3", name: "Postorder Traversal", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-tree-postorder-traversal/description/" }] },
      { id: "tr-4", name: "Level Order Traversal", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/description/" }] },
      { id: "tr-5", name: "ZigZag Level Order Traversal", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/description/" }] },
      { id: "tr-6", name: "Level Order Traversal II", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-tree-level-order-traversal-ii/description/" }] },
      { id: "tr-7", name: "Invert Binary Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/invert-binary-tree/description/" }] },
      { id: "tr-8", name: "Symmetric Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/symmetric-tree/description/" }] },
      { id: "tr-9", name: "Same Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/same-tree/description/" }] },
      { id: "tr-10", name: "Subtree of Another Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/subtree-of-another-tree/description/" }] },
      { id: "tr-11", name: "Flip Equivalent Tree", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/flip-equivalent-binary-trees/description/" }] },
      { id: "tr-12", name: "LCA of Binary Tree", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description/" }] },
      { id: "tr-13", name: "Search in a Binary Search Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/search-in-a-binary-search-tree/" }] },
      { id: "tr-14", name: "LCA of BST", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/description/" }] },
      { id: "tr-15", name: "LCA of Deepest Leaves", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/lowest-common-ancestor-of-deepest-leaves/description/" }] },
      { id: "tr-16", name: "Two Sum IV (BST)", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/description/" }] },
      { id: "tr-17", name: "Kth Smallest Element in BST", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/description/" }] },
      { id: "tr-18", name: "Minimum Depth of Binary Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/minimum-depth-of-binary-tree/description/" }] },
      { id: "tr-19", name: "Maximum Depth of Binary Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/description/" }] },
      { id: "tr-20", name: "Balanced Binary Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/balanced-binary-tree/description/" }] },
      { id: "tr-21", name: "Diameter of Binary Tree", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/diameter-of-binary-tree/description/" }] },
      { id: "tr-22", name: "Check Completeness of Binary Tree", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/check-completeness-of-a-binary-tree/description/" }] },
      { id: "tr-23", name: "Validate BST", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/validate-binary-search-tree/description/" }] },
      { id: "tr-24", name: "Recover BST", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/recover-binary-search-tree/description/" }] },
      { id: "tr-25", name: "Path Sum", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/path-sum/description/" }] },
      { id: "tr-26", name: "Path Sum II", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/path-sum-ii/" }] },
      { id: "tr-27", name: "Sum of Root to Leaf Numbers", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/sum-root-to-leaf-numbers/description/" }] },
      { id: "tr-28", name: "Maximum Path Sum", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/description/" }] },
      { id: "tr-29", name: "Construct Tree from Preorder and Inorder", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description/" }] },
      { id: "tr-30", name: "Construct Tree from Postorder and Inorder", difficulty: "medium", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/description/" }] },
      { id: "tr-31", name: "Sorted Array to BST", difficulty: "easy", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/" }] },
      { id: "tr-32", name: "Serialize and Deserialize Binary Tree", difficulty: "hard", links: [{ label: "LeetCode", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/description/" }] },
    ],
  },
];

export const totalQuestions = patterns.reduce((sum, p) => sum + p.questions.length, 0);
